spring:
  application:
    name: coffeemachine
  profiles:
    active:
    - 'prod'
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: 'http://localhost:8071'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://localhost:8070/eureka
 
info:
  app:
    name: "Coffees"
    description: "Coffee Machine"
    version: "2.0"
